### ISSUE TITLE
WebpackError at /accounts/login/

### ISSUE THREAD

**Issue by gundarskorats** [RTIInternational/SMART#155]
OS: Ubuntu 20.04 
Problem: Followed installation instructions successfully (no errors during building process), but encountered with WebpackError at /accounts/login/.
Any suggestions how to solve this?

<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">WebpackError at /accounts/login/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">            ModuleBuildError in 
            Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "...     floor(math": expected expression (e.g. 1px, bold), was ".div($grid-gutter-w"
        on line 369 of node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss
        from line 8 of node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss
        from line 2 of src/styles/_base.scss
        from line 5 of src/styles/_includes.scss
        from line 2 of src/styles/smart.scss
&gt;&gt; vbar-padding-horizontal:        floor(math.div($grid-gutter-width, 2)) !defa
   ------------------------------------------^

    at processResult (/code/node_modules/webpack/lib/NormalModule.js:753:19)
    at /code/node_modules/webpack/lib/NormalModule.js:855:5
    at /code/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /code/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/code/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.callback (/code/node_modules/sass-loader/dist/index.js:54:7)
    at Object.done [as callback] (/code/node_modules/neo-async/async.js:8069:18)
    at options.error (/code/node_modules/node-sass/lib/index.js:293:32)
            </pre>

Request Method: | GET
-- | --
http://localhost:8000/accounts/login/?next=/projects/
3.2.9
WebpackError
ModuleBuildError in              Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js): ModuleBuildError: Module build failed (from ../node_modules/sass-loader/dist/cjs.js): SassError: Invalid CSS after "...     floor(math": expected expression (e.g. 1px, bold), was ".div($grid-gutter-w"         on line 369 of node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss         from line 8 of node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss         from line 2 of src/styles/_base.scss         from line 5 of src/styles/_includes.scss         from line 2 of src/styles/smart.scss >> vbar-padding-horizontal:        floor(math.div($grid-gutter-width, 2)) !defa    ------------------------------------------^      at processResult (/code/node_modules/webpack/lib/NormalModule.js:753:19)     at /code/node_modules/webpack/lib/NormalModule.js:855:5     at /code/node_modules/loader-runner/lib/LoaderRunner.js:399:11     at /code/node_modules/loader-runner/lib/LoaderRunner.js:251:18     at context.callback (/code/node_modules/loader-runner/lib/LoaderRunner.js:124:13)     at Object.callback (/code/node_modules/sass-loader/dist/index.js:54:7)     at Object.done [as callback] (/code/node_modules/neo-async/async.js:8069:18)     at options.error (/code/node_modules/node-sass/lib/index.js:293:32)
/usr/local/lib/python3.8/site-packages/webpack_loader/loader.py, line 117, in get_bundle
/usr/local/bin/python
3.8.12
['/code',  '/code',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/site-packages']
Tue, 08 Mar 2022 06:44:18 +0000

Error during template rendering
In template /code/smart/templates/base.html, error at line 20

ModuleBuildError in Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js): ModuleBuildError: Module build failed (from ../node_modules/sass-loader/dist/cjs.js): SassError: Invalid CSS after "... floor(math": expected expression (e.g. 1px, bold), was ".div($grid-gutter-w" on line 369 of node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss from line 8 of node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss from line 2 of src/styles/_base.scss from line 5 of src/styles/_includes.scss from line 2 of src/styles/smart.scss >> vbar-padding-horizontal: floor(math.div($grid-gutter-width, 2)) !defa ------------------------------------------^ at processResult (/code/node_modules/webpack/lib/NormalModule.js:753:19) at /code/node_modules/webpack/lib/NormalModule.js:855:5 at /code/node_modules/loader-runner/lib/LoaderRunner.js:399:11 at /code/node_modules/loader-runner/lib/LoaderRunner.js:251:18 at context.callback (/code/node_modules/loader-runner/lib/LoaderRunner.js:124:13) at Object.callback (/code/node_modules/sass-loader/dist/index.js:54:7) at Object.done [as callback] (/code/node_modules/neo-async/async.js:8069:18) at options.error (/code/node_modules/node-sass/lib/index.js:293:32)

**Comment by AstridKery** [comment]
Hi @gundarskorats ! This appears to be a new error in master which is occurring for us as well. I'm not seeing it in our dev branches so I'm going to look at what's different.

**Comment by AstridKery** [comment]
Ok a fix has been merged into master. Turns out the yarn.lock file was not updated when the package.json file was. Please pull the changes and rebuild. You may need to use the flag --no-cache when running docker-compose build.
