### ISSUE TITLE
Service 'smart_frontend' failed to build

### ISSUE THREAD

**Issue by maxuboldi** [RTIInternational/SMART#182]
=> ERROR [7/7] RUN yarn add --force node-sass                                                                                                                                                       7.6s 
------                                                                                                                                                                                                    
 > [7/7] RUN yarn add --force node-sass:                                                                                                                                                                  
#11 0.282 yarn add v1.22.19                                                                                                                                                                               
#11 0.333 [1/4] Resolving packages...                                                                                                                                                                     
#11 1.626 [2/4] Fetching packages...                                                                                                                                                                      
#11 3.579 [3/4] Linking dependencies...                                                                                                                                                                   
#11 3.581 warning " > babel-loader@7.1.5" has incorrect peer dependency "webpack@2 || 3 || 4".
#11 3.581 warning " > optimize-css-assets-webpack-plugin@5.0.8" has incorrect peer dependency "webpack@^4.0.0".
#11 5.812 [4/4] Rebuilding all packages...
#11 7.420 error /code/node_modules/node-sass: Command failed.
#11 7.420 Exit code: 1
#11 7.420 Command: node scripts/build.js
#11 7.420 Arguments: 
#11 7.420 Directory: /code/node_modules/node-sass
#11 7.420 Output:
#11 7.420 Building: /usr/local/bin/node /code/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
#11 7.420 gyp info it worked if it ends with ok
#11 7.420 gyp verb cli [
#11 7.420 gyp verb cli   '/usr/local/bin/node',
#11 7.420 gyp verb cli   '/code/node_modules/node-gyp/bin/node-gyp.js',
#11 7.420 gyp verb cli   'rebuild',
#11 7.420 gyp verb cli   '--verbose',
#11 7.420 gyp verb cli   '--libsass_ext=',
#11 7.420 gyp verb cli   '--libsass_cflags=',
#11 7.420 gyp verb cli   '--libsass_ldflags=',
#11 7.420 gyp verb cli   '--libsass_library='
#11 7.420 gyp verb cli ]
#11 7.420 gyp info using node-gyp@8.4.1
#11 7.420 gyp info using node@14.19.3 | linux | arm64
#11 7.420 gyp verb command rebuild []
#11 7.420 gyp verb command clean []
#11 7.420 gyp verb clean removing "build" directory
#11 7.420 gyp verb command configure []
#11 7.420 gyp verb find Python Python is not set from command line or npm configuration
#11 7.420 gyp verb find Python Python is not set from environment variable PYTHON
#11 7.420 gyp verb find Python checking if "python3" can be used
#11 7.420 gyp verb find Python - executing "python3" to get executable path
#11 7.420 gyp verb find Python - executable path is "/usr/bin/python3"
#11 7.420 gyp verb find Python - executing "/usr/bin/python3" to get version
#11 7.420 gyp verb find Python - version is "3.5.3"
#11 7.420 gyp verb find Python - version is 3.5.3 - should be >=3.6.0
#11 7.420 gyp verb find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
#11 7.420 gyp verb find Python checking if "python" can be used
#11 7.420 gyp verb find Python - executing "python" to get executable path
#11 7.420 gyp verb find Python - executable path is "/usr/bin/python"
#11 7.420 gyp verb find Python - executing "/usr/bin/python" to get version
#11 7.420 gyp verb find Python - version is "2.7.13"
#11 7.420 gyp verb find Python - version is 2.7.13 - should be >=3.6.0
#11 7.420 gyp verb find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
#11 7.420 gyp ERR! find Python 
#11 7.420 gyp ERR! find Python Python is not set from command line or npm configuration
#11 7.420 gyp ERR! find Python Python is not set from environment variable PYTHON
#11 7.420 gyp ERR! find Python checking if "python3" can be used
#11 7.420 gyp ERR! find Python - executable path is "/usr/bin/python3"
#11 7.420 gyp ERR! find Python - version is "3.5.3"
#11 7.420 gyp ERR! find Python - version is 3.5.3 - should be >=3.6.0
#11 7.420 gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
#11 7.420 gyp ERR! find Python checking if "python" can be used
#11 7.420 gyp ERR! find Python - executable path is "/usr/bin/python"
#11 7.420 gyp ERR! find Python - version is "2.7.13"
#11 7.420 gyp ERR! find Python - version is 2.7.13 - should be >=3.6.0
#11 7.420 gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
#11 7.420 gyp ERR! find Python 
#11 7.420 gyp ERR! find Python **********************************************************
#11 7.420 gyp ERR! find Python You need to install the latest version of Python.
#11 7.420 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#11 7.420 gyp ERR! find Python you can try one of the following options:
#11 7.420 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#11 7.420 gyp ERR! find Python   (accepted by both node-gyp and npm)
#11 7.420 gyp ERR! find Python - Set the environment variable PYTHON
#11 7.420 gyp ERR! find Python - Set the npm configuration variable python:
#11 7.420 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#11 7.420 gyp ERR! find Python For more information consult the documentation at:
#11 7.420 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#11 7.420 gyp ERR! find Python **********************************************************
#11 7.420 gyp ERR! find Python 
#11 7.420 gyp ERR! configure error 
#11 7.420 gyp ERR! stack Error: Could not find any Python installation to use
#11 7.420 gyp ERR! stack     at PythonFinder.fail (/code/node_modules/node-gyp/lib/find-python.js:330:47)
#11 7.420 gyp ERR! stack     at PythonFinder.runChecks (/code/node_modules/node-gyp/lib/find-python.js:159:21)
#11 7.420 gyp ERR! stack     at PythonFinder.<anonymous> (/code/node_modules/node-gyp/lib/find-python.js:266:16)
#11 7.420 gyp ERR! stack     at PythonFinder.execFileCallback (/code/node_modules/node-gyp/lib/find-python.js:297:7)
#11 7.420 gyp ERR! stack     at ChildProcess.exithandler (child_process.js:374:7)
#11 7.420 gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
#11 7.420 gyp ERR! stack     at maybeClose (internal/child_process.js:1088:16)
#11 7.420 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
#11 7.420 gyp ERR! System Linux 5.10.104-linuxkit
#11 7.420 gyp ERR! command "/usr/local/bin/node" "/code/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#11 7.420 gyp ERR! cwd /code/node_modules/node-sass
#11 7.420 gyp ERR! node -v v14.19.3
#11 7.420 gyp ERR! node-gyp -v v8.4.1
#11 7.420 gyp ERR! not ok 
#11 7.420 Build failed with error code: 1
#11 7.421 info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
------
executor failed running [/bin/sh -c yarn add --force node-sass]: exit code: 1
ERROR: Service 'smart_frontend' failed to build : Build failed

**Comment by lizehaodashuaibi** [comment]
hi, i have the same question. Have you solved it?

**Comment by AstridKery** [comment]
Hi, are you trying to build the production version? I'm not seeing this issue when building from dev. The production version has some known issues that we are fixing in our upcoming version 3.0. For now I suggest you try building using the `rebuild.sh` script in `envs/dev`

**Comment by maxuboldi** [comment]
Hi, no, if I remember correctly, the problem was with the development version and at the time I was able to solve it by modifying some things in the repo, but I don't remember exactly what because it was a long time ago. Thanks.
